services:
  yoga-debug:
    volumes:
      - ../../:/zero
      - ./build/:/src
    image: "emscripten/emsdk"
    command: bash -c "emcmake cmake -DCMAKE_BUILD_TYPE=Debug -S /zero/puttyknife/yoga-wasm -B ./yoga-debug && cmake --build ./yoga-debug"
  yoga-release:
    volumes:
      - ../../:/zero
      - ./build/:/src
    image: "emscripten/emsdk"
    command: bash -c "emcmake cmake -DCMAKE_BUILD_TYPE=Release -S /zero/puttyknife/yoga-wasm -B ./yoga-release && cmake --build ./yoga-release"
    
