export * from './shared/index.js';

export const {
    Vector,
    FloatVector,
    Uint32Vector,
    StringVector,
    BufferInfo,
    DescriptorSetLayoutBinding,
    DescriptorSetLayoutBindingVector,
    DescriptorSetLayoutInfo,
    TextureInfo,
    TextureVector,
    FramebufferInfo,
    AttachmentDescription,
    AttachmentDescriptionVector,
    RenderPassInfo,
    SamplerInfo,
    ShaderInfo,
    DescriptorSetLayoutVector,
    PipelineLayoutInfo,
    VertexAttribute,
    VertexAttributeVector,
    BufferVector,
    VertexInput,
    IndexInput,
    InputAssembler,
    RasterizationState,
    DepthStencilState,
    BlendState,
    PassState,
    VertexInputAttributeDescription,
    VertexInputBindingDescription,
    VertexInputAttributeDescriptionVector,
    VertexInputBindingDescriptionVector,
    VertexInputState,
    PipelineInfo,
    SubmitInfo,

    Buffer,
    CommandBuffer,
    DescriptorSet,
    DescriptorSetLayout,
    Device,
    Fence,
    Framebuffer,
    Pipeline,
    PipelineLayout,
    Queue,
    RenderPass,
    Sampler,
    Semaphore,
    Shader,
    Texture
} = (globalThis as any).gfx;
